sonar.projectKey=Andrea_Loyola_t1
sonar.sources=src
sonar.exclusions=**/*.pyc, **/__pycache__/**, **/*.xml
sonar.host.url=https://sonarqube.ingsoftware.lat/
sonar.token=sqa_4e296de25b56b315988b9a9dfd137d2b4f97e7c3

# CONFIGURACIÓN DE PRUEBAS Y COBERTURA
sonar.tests=tests
sonar.test.inclusions=**/*.py
sonar.python.coverage.reportPaths=coverage.xml
